name: Deploying VuePress project to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

env: # 设置环境变量
  TZ: Asia/Shanghai # 设置时区为上海时间

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout # 检出仓库源码
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }} # 安装 Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn' # 启用 Yarn 缓存

      - name: Install dependencies and build # 安装依赖并构建
        run: |
          yarn
          yarn build

      - name: Deploy to GitHub Pages # 部署到 GitHub Pages
        run: |
          # 获取 Git 仓库信息
          commit_info=`git describe --all --always --long`
          user_name=`git log -1 --pretty=format:'%an'`
          user_email=`git log -1 --pretty=format:'%ae'`
          deploy_branch=gh-pages

          # 进入构建输出目录
          cd docs/.vuepress/dist

          # 设置 Git 配置
          git config --global init.defaultBranch $deploy_branch
          git init
          git config user.name ${user_name}
          git config user.email ${user_email}

          # 保留 .git 目录和历史记录
          git remote add origin https://github.com/${{ github.repository }}.git
          git fetch origin $deploy_branch --depth=1 || echo "No existing gh-pages branch"

          # 合并上一次部署的历史记录
          git checkout -b $deploy_branch origin/$deploy_branch || git checkout -b $deploy_branch

          # 添加新的构建文件
          rsync -av --delete --exclude='.git' . ../dist_repo/
          cd ../dist_repo

          # 提交并推送到 gh-pages 分支
          git add -A
          git commit -m "auto deploy, $commit_info" || echo "No changes to commit"
          git push origin HEAD:$deploy_branch --force
