name: Deploying VuePress project to GitHub Pages

# 在master分支发生push事件时触发。
on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs: # 工作流
  build:
    runs-on: ubuntu-latest #运行在虚拟机环境ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout # 步骤1
        uses: actions/checkout@v4 # 使用的动作。格式：userName/repoName。作用：检出仓库，获取源码。 官方actions库：https://github.com/actions
      - name: Use Node.js ${{ matrix.node-version }} # 步骤2
        uses: actions/setup-node@v4 # 作用：安装nodejs
        with:
          node-version: ${{ matrix.node-version }} # 版本
      - name: run deploy.sh
        run: npm install && npm run deploy # 执行的命令
